### ISSUE TITLE
Edit Modified Date

### ISSUE THREAD

**Issue by X-Raym** [aaemnnosttv/last-modified-timestamp#1]
Hi !
would it be possible to edit the modifed date ?

thanks :)

**Comment by aaemnnosttv** [comment]
Hi there!  Wow, sorry about the delay here, but this one flew under my radar.  Better late than never?

Thanks for the request, but I plan on keeping this plugin read-only in regards to post dates.

Thanks again for your feedback :)

**Comment by X-Raym** [comment]
Since 2014, I now know how to modify it to my needs hehe :P

Thanks for your support anyway, and thank for your plugin (that I still use on some websites :) )
